name: Workflow Test

on:
  push:
    branches:
      - '**' #Trigger on any branch

jobs:
  lint:
    name: Run .NET Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.407'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run dotnet format
        run: dotnet format --verify-no-changes --severity warn